[metadata]
version = "1.0"

[versions]
# Gradle Plugins/Deps
kotlin = "1.7.10"
indra = "3.1.2"
licenser = "0.6.1"
shadow = "8.1.1"

# Common Dependencies
adventure = "4.14.0"
cloud = "1.8.3"
configurate = "4.1.2"

# Storage Drivers
morphia = "2.3.6"

# platform: paper
paper = "1.20.1-R0.1-SNAPSHOT"

[plugins]
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
licenser = { module = "gradle.plugin.org.cadixdev.gradle:licenser", version.ref = "licenser" }
shadow = { module = "com.github.johnrengelman:shadow", version.ref = "shadow" }

# build
indra = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-sonatype = { module = "net.kyori:indra-publishing-sonatype", version.ref = "indra" }

# Common Dependencies
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
cloud-core = { module = "cloud.commandframework:cloud-core", version.ref = "cloud" }
cloud-minecraft-extras = { module = "cloud.commandframework:cloud-minecraft-extras", version.ref = "cloud" }
cloud-annotations = { module = "cloud.commandframework:cloud-annotations", version.ref = "cloud" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-extra-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.7" }

# Storage Drivers
morphia-core = { module = "dev.morphia.morphia:morphia-core", version.ref = "morphia" }
morphia-kotlin = { module = "dev.morphia.morphia:morphia-kotlin", version.ref = "morphia" }

# platform: paper
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
cloud-paper = { module = "cloud.commandframework:cloud-paper", version.ref = "cloud" }