[metadata]
version = "1.0"

[versions]
# Gradle Plugins/Deps
kotlin = "1.7.10"
indra = "3.1.2"
licenser = "0.6.1"

# Common Dependencies

# platform: paper
paper = "1.20.1-R0.1-SNAPSHOT"

[plugins]
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}
licenser = { module = "gradle.plugin.org.cadixdev.gradle:licenser", version.ref = "licenser" }

# build
indra = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-sonatype = { module = "net.kyori:indra-publishing-sonatype", version.ref = "indra" }

# Common Dependencies

# platform: paper
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }